#!/bin/sh

# SPDX-PackageSummary: mcxRescue-live-build
# SPDX-FileComment: mcxRescue Template Engine Loader
# SPDX-FileCopyrightText: Copyright (C) 2025 Magna Capax Finland Oy
# SPDX-License-Identifier: MPL-2.0

cd /opt
git clone https://github.com/MagnaCapax/mcxRescue