# SPDX-PackageSummary: finnix-live-build
# SPDX-FileCopyrightText: © 2020 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0
---
name: "release"
"on":
  workflow_dispatch:
jobs:
  build:
    name: "Build image (${{ matrix.arch }})"
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: "amd64"
            runs-on: "ubuntu-latest"
          - arch: "arm64"
            runs-on: "ubuntu-24.04-arm"
    runs-on: "${{ matrix.runs-on }}"
    permissions:
      id-token: "write"
      attestations: "write"
    env:
      BUILD_WORKFLOW_TAG: "release"
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: true
      - name: "Dependency packages"
        run: |
          sudo apt update
          tools/get-dependencies --only required -0 | xargs -0 sudo apt -y install
          tools/get-dependencies --only optional | while IFS='' read -r pkg; do
            sudo apt -y install "${pkg}" || true
          done
      - name: "Build image"
        run: |
          # Prepare
          env | grep ^GITHUB_ | sudo tee -a /etc/environment >/dev/null
          sudo chown -R root:root .

          # Main ISO image
          sudo env BUILD_TAGS="${BUILD_WORKFLOW_TAG}" ./finnix-live-build

          # Source ISO
          TEMP_BUILD_DIR="$(sudo mktemp -d -p "$(pwd)/build")"
          sudo env SOURCE_ISO=true BUILD_DIR="${TEMP_BUILD_DIR?}" ./finnix-live-build
          sudo mv "${TEMP_BUILD_DIR}/lb/mcxRescue-source.iso" build/lb/
          sudo rm -rf "${TEMP_BUILD_DIR?}"
          echo "Note: The build information listed above is not used; only the source ISO is saved."
          echo "See the 'Build image' step for actual build information."

          # Cleanup
          sudo chown -R "$(id -un):$(id -gn)" .
      - name: "Attest"
        uses: "actions/attest-build-provenance@v3"
        with:
          subject-path: "${{ github.workspace }}/build/lb/mcxRescue-*.iso"
      - name: "Upload artifacts"
        uses: "actions/upload-artifact@v4"
        with:
          name: "mcxRescue-live-build.${{ github.workflow }}.${{ github.job }}.${{ matrix.arch }}.${{ github.run_number }}.${{ github.run_id }}"
          path: |
            build/lb/mcxRescue-*
            build/lb/chroot.files
            build/lb/chroot.packages.*
          # Faster uploads as ISOs are already heavily compressed
          compression-level: 0
  build-docker:
    name: "Build Docker image (${{ matrix.arch }})"
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: "amd64"
            runs-on: "ubuntu-latest"
          - arch: "arm64"
            runs-on: "ubuntu-24.04-arm"
    runs-on: "${{ matrix.runs-on }}"
    permissions:
      id-token: "write"
      contents: "read"
      packages: "write"
      attestations: "write"
    env:
      BUILD_WORKFLOW_TAG: "release"
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: true
      - name: "Authentication"
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: "Dependency packages"
        run: |
          sudo apt update
          tools/get-dependencies --only required -0 | xargs -0 sudo apt -y install
          tools/get-dependencies --only optional | while IFS='' read -r pkg; do
            sudo apt -y install "${pkg}" || true
          done
      - name: "Set environment variables"
        run: |
          IMAGE_NAME="$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')"
          IMAGE_TAG="${BUILD_WORKFLOW_TAG}-${{ matrix.arch }}"
          echo "IMAGE_NAME=${IMAGE_NAME}" >>"${GITHUB_ENV}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >>"${GITHUB_ENV}"
      - name: "Build image"
        run: |
          IMAGE_ID="ghcr.io/${IMAGE_NAME}:${IMAGE_TAG}"
          env BUILD_TAGS="${BUILD_WORKFLOW_TAG}" DOCKER_BUILD="true" ./finnix-live-build
          docker image build -t "${IMAGE_ID}" build/docker
          docker image history "${IMAGE_ID}"
          docker image inspect "${IMAGE_ID}"
          docker image push "${IMAGE_ID}"
          IMAGE_DIGEST="sha256:$(docker buildx imagetools inspect "${IMAGE_ID}" --raw | sha256sum | awk '{print $1}')"
          echo "IMAGE_DIGEST=${IMAGE_DIGEST}" >>"${GITHUB_ENV}"
      - name: "Attest"
        uses: "actions/attest-build-provenance@v3"
        with:
          subject-name: "ghcr.io/${{ env.IMAGE_NAME }}"
          subject-digest: "${{ env.IMAGE_DIGEST }}"
          push-to-registry: true
